### ISSUE TITLE
Visitation

### ISSUE THREAD

**Issue by samkellett** [eggs-cpp/variant#14]
Does Eggs.Variant support element visitation? I've had a look through the reference but can't see any method (except maybe `apply`, is that what I'm looking for?).

**Comment by K-ballo** [comment]
Have a look at the [`apply`](http://eggs-cpp.github.io/variant/reference.html#eggs-apply) functions, they will invoke a callable with the current active member of the variant.

**Comment by samkellett** [comment]
yep that works! thanks
