### ISSUE TITLE
support for recursive_wrapper

### ISSUE THREAD

**Issue by tomilov** [eggs-cpp/variant#15]
Do you plan to introduce the support for `recursive_wrapper` like `boost::variant` have?
I know, that common wrapping of incomplete types breaks type traits on whole `variant` type, but imposing constraints on using such `variant` types makes they still useful.

**Comment by K-ballo** [comment]
No, not like `boost::variant`, see #12. If I ever finish scoped allocator support I might post an example of how a non-intrusive `recursive_wrapper` would look like.

**Comment by tomilov** [comment]
How AST would looks like if one use non-intrusive recursive types of nodes?

**Comment by K-ballo** [comment]
I do not really know yet, why don't you tell me? You can implement a non-intrusive `recursive_wrapper` yourself, it's just a smart pointer / reference wrapper hybrid of sorts. Otherwise, you will have to wait for me to write that example I mentioned earlier.

**Comment by tomilov** [comment]
[I implement it](https://github.com/tomilov/variant/blob/triviality/include/versatile/recursive_wrapper.hpp), but then I don't know what does it means "non-intrusive" though. Commented part of enabler does not work with incomplete types. If I use it without enabler, then variant containing such wrapped type not mimic underlying type in some use-cases (during construction and especially default-construction).

**Comment by K-ballo** [comment]
> I implement it, but then I don't know what does it means "non-intrusive" though.

It means without touching a single bit of `eggs::variant` internals.

> Commented part of enabler does not work with incomplete types.

That declaration requires a complete type, yes.

> If I use it without enabler, then variant containing such wrapped type not mimic underlying type in some use-cases (during construction and especially default-construction).

I'm not sure I get this, do you have a minimal test case that reproduces the issue?

**Comment by tomilov** [comment]
Something similar to `struct X { X(int) { ; } }; static_assert(!std::is_default_constructible_v< X >); using R = recursive_wrapper< X >; static_assert(std::is_default_constructible_v< R >);`. And even further (e.g. for [my variant implementation](https://github.com/tomilov/variant), for which non-empty guarantee holds and it is default-constructible (leftmost default-constructible alternative type default-constructed if any)).

**Comment by K-ballo** [comment]
A never-empty variant is a completely different beast, and I can imagine you having trouble there with a non intrusive recursive wrapper, but `eggs::variant` is **not** a never-empty variant.

Do you have a minimal test case that reproduces an issue with the implementation in **this** repository?

**Comment by tomilov** [comment]
Hopefully it is impossible for `eggs::variant`, due to it is not never-empty.

**Comment by K-ballo** [comment]
I'm closing this as invalid. Feel free to reopen with a minimal test case reproducing an issue with `eggs::variant`.

**Comment by tomilov** [comment]
I don't know maybe it is flaw of `union` part of implementation of `clang`, that I use, but I can't even try to apply a type trait for `eggs::variant`.

    struct S {};
    static_assert(!std::is_constructible_v< S, int >);
    using V = ::eggs::variant< recursive_wrapper< S > >;
    static_assert(std::is_constructible_v< V, int >);

**Comment by K-ballo** [comment]
That is not a flaw in _Clang_'s implementation of `union`, you could see the exact same behavior if you replace `eggs::variant` with `std::tuple`.

This has to do with the language rules for `constexpr`, that require constexpr functions to be instantiated when used in unevaluated contexts. AFAIK this is currently only implemented by _Clang_, and is being tracked by [CWG1581](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#1581).
