### ISSUE TITLE
Heterogenous multi-visitation ?

### ISSUE THREAD

**Issue by jcelerier** [eggs-cpp/variant#22]
Hello,

Is there a way to make multi-visitation with apply() & multiple variant types ? 

e.g.

    eggs::variant<int, float> v1;
    eggs::variant<foo, bar> v2;

    struct vis { 
        void operator()(int, foo);
        void operator()(int, bar);
        void operator()(float, foo);
        void operator()(float, bar);
    };
    
    eggs::variants::apply(vis{}, v1, v2);

thanks !

**Comment by tomilov** [comment]
@jcelerier You can do it easily by yourself. Here is an example https://github.com/tomilov/variant/blob/master/include/versatile/visit.hpp#L165 of multivisit function.

**Comment by K-ballo** [comment]
> Is there a way to make multi-visitation with apply() & multiple variant types ?

Yes, exactly as you have written it. Have you run into any issues while trying that snippet?

**Comment by K-ballo** [comment]
> You can do it easily by yourself.

@tomilov Why would he want to do it by himself when the library has provided it since day one? What am I missing here?

**Comment by tomilov** [comment]
@K-ballo I'm sorry. Moreover I even knew it, but I hastened to write this irrelevant answer. My mistake.

**Comment by jcelerier** [comment]
damn, yes, this simple example works, but more complex ones don't. I'll try to make a simple reproducible example (if this is not some stupid mistake from my part :) ). Sorry for the noise !
