### ISSUE TITLE
Dispatching triviality of copy/move-construction/assignment all together

### ISSUE THREAD

**Issue by tomilov** [eggs-cpp/variant#23]
All mentioned operations, expressed by corresponding special functions, are all the same by its nature.
Say, both copy-construction/assignment and move-construction/assignment is just a *copy* (in both cases!) of memory from one (source, right hand side) properly aligned and sized storage to another (destination, left hand side) (possibly uninitialized). There is not any difference between all of them. The (imaginary) difference arised when considered some artificial class with forced assymetry in mentioned special functions (i.e. some of them are user-provided or explicitly deleted, but others are defaulted). But such a class can be considered as oxymoron, because having (any) one of copy/move-constructor/assignment operator one can emulate each other absolutely legally by using this single existing special function to copy source memory to destination (or simply using `std::memcpy`). Hence, it make sense to only consider types with all trivial mentioned special functions or with not trivial of all of them.

I think it means, that (in real life) there is no need to dispatch triviality of all the possible combinations for all four (or even eight, if we consider `const &&` and `&` along with `const &` and `&&`) special functions. If any one of them is not trivial, then all others should be treated as not trivial too (but (instead) maybe converse is right if triviality has logical priority).

What do you think about this?

**Comment by tomilov** [comment]
Oh, I had a slight misconception about `eggs::variant` implementation. It doesn't dispatch `std::is_trivially_copy/move_*` cases separately, but only `std::is_trivially_copyable` case. On the one hand [TriviallyCopyable](http://en.cppreference.com/w/cpp/concept/TriviallyCopyable) does imply that destructor is not deleted and is trivial (it seems superfluous to have both `std::is_trivially_copyable` and `std::is_trivially_destructible` [here](https://github.com/eggs-cpp/variant/blob/master/include/eggs/variant/detail/storage.hpp#L713)). On the other hand there is [such a note](http://stackoverflow.com/a/36164788/1430927), which strongly advices against of using `std::is_trivially_copyable`.

**Comment by K-ballo** [comment]
I don't understand what the point of this issue is. Could you please clarify, @tomilov?

**Comment by tomilov** [comment]
You may close it. Initially it was a mistake. But in second comment I point you at line in code, which containing mistake.

**Comment by K-ballo** [comment]
Alright, I'd like to close this as it seems to be completely unrelated to Eggs.Variant design and/or implementation. But what about that mistake you mention? I don't see any. If you are referring to [this line](https://github.com/eggs-cpp/variant/blob/master/include/eggs/variant/detail/storage.hpp#L713) you should keep in mind that while all trivially-copyable types are trivially-destructible, the converse is not true; some types are trivially-destructible but not trivially-copyable.

For future reference, you should consider taking a look at my articles where many of these design decisions and technical limitations are explored and explained.

**Comment by tomilov** [comment]
Your articles — that's what brought me here. Now I see there is no `_storage< pack<...>, true, false >`. I was mistaken.
