### ISSUE TITLE
Provide a prefix for options defined in CMakeLists.txt

### ISSUE THREAD

**Issue by samkellett** [eggs-cpp/variant#24]
Currently eggs-variant has a WITH_TESTS option that I can set when I have eggs-variant included as a sub directory in my cmake project. However, this variable name doesn't obviously belong to eggs-variant, so when I run: `cmake -DWITH_TESTS=Off ..` it is unclear that I simply do not want to run the variant tests. Maybe naming the variable EGGS_WITH_TESTS or EGGS_VARIANT_WITH_TESTS would be better?

**Comment by K-ballo** [comment]
08c644df929dc9b56704cd63bdd980802f871b36 uses a prefixed option when included as a subdirectory, please give it a try.

**Comment by samkellett** [comment]
that works great. thanks!
