### ISSUE TITLE
why not improve to C++14

### ISSUE THREAD

**Issue by qicosmos** [eggs-cpp/variant#26]
So many micro, no elegant simplicity.
Hope you can improve to C++14.

**Comment by viboes** [comment]
Can you elaborate?

**Comment by qicosmos** [comment]
I think C++14 can clean code, maybe i can try in future.

**Comment by tomilov** [comment]
@qicosmos Which features of C++14 namely you mean?

**Comment by qicosmos** [comment]
I mean that you define EGGS_CXX11_xxx micros, i think is not necessary, you can just surpport c++14, and the cxx11 micros can be removed, and then the code will be more simple.

**Comment by tomilov** [comment]
@qicosmos From [README](https://github.com/eggs-cpp/variant/blob/master/README.md) (emphasis mine): Eggs.Variant is a C++**11**/14 generic, type-safe, discriminated union.

**Comment by qicosmos** [comment]
@tomilov 
I konw, however i don't think it is necessary, if you don't think so, i close this issue.
thanks for your reply.

**Comment by tomilov** [comment]
@qicosmos Note I'm not the author of the library.

**Comment by K-ballo** [comment]
@qicosmos library author here, thank you for your report. It is true as you say that C++11 support isn't necessary &mdash;nor is C++14&mdash;, but that support is a conscious decision to extend the usability of the library as long as it does not compromise experimentation with the design.

With regards to the `EGGS_CXX11_*` macros, those are not there to support C++11 but to support compilers that aren't feature complete. If every supported compiler would fully and properly support C++11 then most or all of those macros would be gone.
