### ISSUE TITLE
Compiling error VS 2015 Update 3

### ISSUE THREAD

**Issue by purell** [eggs-cpp/variant#29]
Hi,

I'm using Visual Studio 2015 Update 3 and I'm getting this 
error. I use the commit 91dae8040425e51aab24d25788336063e1c6837e

![image](https://user-images.githubusercontent.com/7946730/38214480-b8a98678-3692-11e8-8d6e-3c1c2a7ad253.png)

Commenting this line (28) make the compilation succeed.

**Comment by K-ballo** [comment]
Hi @purell,

I cannot reproduce this on `master` using Visual Studio 2015 Update 3. Could you provide me with detailed steps to reproduce the issue?

From the screenshot, it looks like it is not a build error but rather an IntelliSense error.

**Comment by purell** [comment]
@K-ballo You are right, it's an Intellisense error. I'm coming from VS 2008 and Intellisense worked much better than on 2015. I'm always getting weird error or a message saying that `Intellisens has not finished parsing` and sometime it never end so I don't know why I'm still using VS as Notepad++ can do the same if I can't get Intellisense working well as before ;)

Anyway, do you know why I'm getting this Intellisense error ? Do you get it too ? It's a fresh installation without any plugins or extension installed. My exact version is
`Visual Studio Professional 2015 Version 14.0.25431.01 Update 3`

**Comment by K-ballo** [comment]
@purell I do not, I am not able to reproduce the error. My exact version is too `14.0.25431.01 Update 3`. My steps are create a new empty project, configure additional include directories, add a new source file, and finally `#include <eggs/variant.hpp>`, then build (successfully).

What are the detailed steps you make that lead to reproducing this issue?

**Comment by purell** [comment]
Sorry for the delay. Your version is the same as mine.

I started a new empty project and I'm getting the same Intellisense error

![image](https://user-images.githubusercontent.com/7946730/38311467-3b19a420-37ed-11e8-8974-819ec815865d.png)

**Comment by K-ballo** [comment]
Created a new console project, copied the contents of `include/` to the project location, then typed the code from your screenshot:

![image](https://user-images.githubusercontent.com/1700391/38312061-21b46ccc-37f7-11e8-8f88-a7ee0df6a96b.png)

Cannot reproduce; the project builds fine, and IntelliSense does not complain.

I'm going to suggest that you ignore the bogus diagnostic, since it's not a real error and there's nothing I can do to try to mitigate it without being able to reproduce it.

**Comment by purell** [comment]
@K-ballo The only difference is that I get the `eggs-cpp` using 

```bash
git clone https://github.com/eggs-cpp/variant.git
```

And then configure additional Include Directories as
![image](https://user-images.githubusercontent.com/7946730/38312413-b182ac9a-37ef-11e8-93bf-f26dc98283c4.png)

But If I'm the only one with this problem, forget it ;)

**Comment by K-ballo** [comment]
I made a new (fresh) attempt, replicating the clone/include scenario: same results.

**Comment by purell** [comment]
Thank you for your time @K-ballo. I reinstall my Visual Studio 2015 but same problem. Just too bad, I'm kind of not lucky with Intellisense 🥇

**Comment by purell** [comment]
Sorry to resurrect this thread but do you have this warning also (at level 4) ?

In file `Visitor.hpp(131)`

![image](https://user-images.githubusercontent.com/7946730/38470776-a6119706-3b35-11e8-8e70-a12963086d86.png)

**Comment by K-ballo** [comment]
> do you have this warning also (at level 4) ?

I do.

It is trivial to tell the warning is bogus, but if you can figure out a rewrite of that expression that silences the report without changing semantics I will consider it.

**Comment by purell** [comment]
Why not ?

```c++
    struct destroy
      : visitor<destroy, void(void*)>
    {
        template <typename T>
        static void call(void* ptr)
        {
            ptr;  <--- This
            static_cast<T*>(ptr)->~T();
        }
    };
```

Doing this silent the warning. I got no warning at all on eggs-variant ;)

**Comment by K-ballo** [comment]
That looks like an expression with no side effects, which is sometimes warned on. I'll give `(void)ptr;` a try, as it looks harmless, and see what CI reports.

**Comment by K-ballo** [comment]
> I'll give (void)ptr; a try, as it looks harmless, and see what CI reports.

This is now f801e971d054341430cb91d79aa0bb4d0bf24330 on `master`.
