### ISSUE TITLE
What is the meaning of unspecified<I> and unspecified<T> 

### ISSUE THREAD

**Issue by viboes** [eggs-cpp/variant#6]

**Comment by K-ballo** [comment]
The remarks specify that the first argument shall be the expression `in_place<I>`/`in_place<T>`. The type of those expressions is unspecified, other than them carrying an `I`/`T`. Isn't this enough? How could I make this clearer?

**Comment by viboes** [comment]
Ok, I see. You don't want to show the result of these expressions. What is the rationale?

Following the C++ standard style, you can use 'see below' and then describe it. The fact to use something that seem a type an is not one is troubling, even if the type is in italics.

**Comment by K-ballo** [comment]
> The fact to use something that seem a type an is not one is troubling, even if the type is in italics.

But it is a type, an ugly type, one that I don't want to show.

- `unspecified<I>` is `in_place_t(detail::pack_c<std::size_t, I>)`
- `unspecified<T>` is `in_place_t(detail::pack<T>)`

**Comment by viboes** [comment]
I see it now, but I was looking for it. My bad of course.

Once one is used to this notation everything is ok. `unspecified<T>` means an unspecified type that depends on T.

It is hard however to think that it can be a function ;-)

**Comment by K-ballo** [comment]
Fixed by d67e69a4b7c8569c7864cae68e05cdf5f9eb32e6

**Comment by viboes** [comment]
Thanks.
