### ISSUE TITLE
Possible infinite recursion on asignment descrption  

### ISSUE THREAD

**Issue by viboes** [eggs-cpp/variant#7]
In

```c++
constexpr variant& operator=(variant const& rhs);
```

description, doesn't "otherwise, calls `*this = {}`" recurse?

The same applies to the move assignment.

**Comment by K-ballo** [comment]
> doesn't "otherwise, calls *this = {}" recurse?

It does (calls move assignment op, recursively). This used to be defined as `*this = nullvariant`, and got ruined when I removed `nullvariant` altogether. Will revise.

**Comment by K-ballo** [comment]
Fixed by 992d696797becd4ff151ff34be6e7c0a203e661f

**Comment by viboes** [comment]
Thanks.
