### ISSUE TITLE
The use of nested use of npos is cumbersome 

### ISSUE THREAD

**Issue by viboes** [eggs-cpp/variant#9]
Nesting the `npos`definition forces a cumbersome syntax `variant<Ts...>::npos`, while `npos`is independent from any `Ts`.

**Comment by K-ballo** [comment]
So does [`std::basic_string<CharT, Traits, Allocator>::npos`](http://en.cppreference.com/w/cpp/string/basic_string/npos), but it is useful nevertheless. It's there when you do a `typedef`, or when you extend `variant` to taint it with actual meaning.

It has no storage, so it is not a QoI concern.

It is explicitly specified as `-1`, so you can just as well use the literal or define your own constant.

**Comment by viboes** [comment]
I'm not against a nested constant as far as there is one constant outside. 
 
`-1` doesn't works, we need `std::size_t(-1)`


The fact that the standard do this way is not a valid reason.
